Repository Galaxia5987/Recode2024, pull requests merged in 2024-08, with the labels that each got.

#11 Add Kotlin language usage reporting
  src/main/kotlin/frc/robot/Robot.kt
Labels: enhancement

#13 Add imports for kotlin usage report
  src/main/kotlin/frc/robot/Robot.kt
Labels: bug, high priority

#30 I hate Enums in kotlin (Fixed CURRENT_MODE Constant)
  src/main/kotlin/frc/robot/Constants.kt
Labels: bug, wtf??
